version: '3.1'

services:
  app:
    build: .
    command: sh -c "npm run build && npm run start"
    volumes:
      - .:/usr/getir/app
      - /usr/getir/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      APP_ENV: ${APP_ENV}
      HOST: ${HOST}
      PORT: ${PORT}
      TZ: ${TZ}
      MONGO_URI: ${MONGO_URI}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:9004/api"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 1m30s
