version: '3.1'

services:
  app:
    build: .
    command: sh -c "npm run build && npm run start"
    volumes:
      - .:/usr/getir/app
      - /usr/getir/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      APP_ENV: ${APP_ENV}
      HOST: ${HOST}
      PORT: ${PORT}
      TZ: ${TZ}
      MONGO_URI: ${MONGO_URI}

