name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_ENV: ${{secrets.APP_ENV}}
      HOST: ${{secrets.HOST}}
      PORT: ${{secrets.PORT}}
      TZ: ${{secrets.TZ}}
      MONGO_URI: ${{secrets.MONGO_URI}}
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'

      - name: Install
        run: npm install

      - name: Testing
        run: npm test
